# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
rojo = "rojo-rbx/rojo@7.4.1"
wally = "UpliftGames/wally@0.3.2"
Blink = "1Axen/Blink@0.11.1"
zap = "red-blox/zap@0.6.3"
# rojo = "rojo-rbx/rojo@6.2.0"